env:
  global:
    - CC_TEST_REPORTER_ID=2edd8d6c07a4ab8b10f755ac231c67e691f6db821bf1925dc04dab2fd525e4b7
addons:
  postgresql: 9.6
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
dist: trusty
language: ruby
rvm:
  - 2.4.1
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake test RAILS_ENV=test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT